### ISSUE TITLE
hide silenced checks

### ISSUE THREAD

**Issue by maxadamo** [sensu/grafana-sensu-go-datasource#18]
Hello.

I'm not sure if this is a request for information, or a feature request. 
I am trying to filter out the checks that have been silenced. I have inspected the json file that I get from sensuctl, and, for a silenced event, I see the following item:

```json
 "check": {
    ...[CUT]...
    "history": [
      ...[CUT]...
      "silenced": [
        "entity:prod-blahblah.domain.org:keepalive"
      ],
```
can you think of a way to get this working? 

![immagine](https://user-images.githubusercontent.com/1710103/77552033-51468980-6eb3-11ea-9172-5876d204854f.png)

**Comment by mariusoe** [comment]
The filtering of silenced checks can be achieved with the next version (1.1.0) of the data source using server-side filtering (response filtering). See also #30 

Closed by #36
