### ISSUE TITLE
release 1.0.3 is incomplete

### ISSUE THREAD

**Issue by maxadamo** [sensu/grafana-sensu-go-datasource#23]
it misses a downloadable version, like we have for the previous versions.

**Comment by nixwiz** [comment]
The downloadable release has been added.

**Comment by maxadamo** [comment]
@nixwiz thanks for your help. But I suspect something is not right and IMO you need to update the file `plugin.json` .

I install the plugin using this command:
```bash
grafana-cli --pluginUrl https://github.com/sensu/grafana-sensu-go-datasource/releases/download/1.0.3/sensu-sensugo-datasource-1.0.3.zip plugins install sensu-sensugo-datasource
```
then, I run:
```bash
grafana-cli plugins ls | grep sensu-sensugo-datasource
```
and I still get version 1.0.2

**Comment by maxadamo** [comment]
I see that interpolates the value, most probably from the tag number, but it's not working:
```
"version": "%VERSION%",
```

**Comment by nixwiz** [comment]
I've uploaded a new release asset, please try again @maxadamo
