### ISSUE TITLE
Develop some "official" Grafana dashboards

### ISSUE THREAD

**Issue by calebhailey** [sensu/grafana-sensu-go-datasource#24]
Some example dashboards that users can then customize would be a big help here. Some users have reported that a simple dashboard that emulates much of the data that's available in the Sensu Go dashboard (but _in Grafana_, where they can correlate Sensu data with other datasources), with a namespace variable & drop-down to switch namespaces would be a huge win.

**Comment by agoddard** [comment]
This dashboard would be an ace start (we've had folks asking whether this specific dashboard is available somewhere) https://blog.sensu.io/visualizing-sensu-go-data-in-grafana
