### ISSUE TITLE
Escaping in entity names using variable cause incorrect lookups

### ISSUE THREAD

**Issue by ninjaslothx** [sensu/grafana-sensu-go-datasource#43]
Using an $entity variable in the query causes entities with a FQDN to have the periods escaped.

Reproduce: 
Have an entity with an FQDN. 
Create entity variable: 
QUERY API entity IN NAMESPACE $namespace SELECT metadata.name LIMIT 0

Create a new query:
![image](https://user-images.githubusercontent.com/56047571/94393968-b9568f00-01b8-11eb-8e9a-7d8760e1641d.png)

Entity filter is not returned as expected. 
Query response shows the periods being escaped but the entity name is in a quoted string. 

```
Object
request:Object
method:"GET"
url:"api/datasources/proxy/103/api/core/v2/namespaces/default/events"
params:Object
fieldSelector:"event.entity.name == "my-host-01\.mydomain\.org""
hideFromInspector:false
response:Array[0]
```

**Comment by mariusoe** [comment]
Hi,

you should be able to use the variable with Grafana's advanced variable
formatting and force the raw value without any escaping: `${entity:raw}`



ninjaslothx <notifications@github.com> schrieb am Mo., 28. Sept. 2020,
07:31:

**Comment by ninjaslothx** [comment]
That has resolved the issue! 
Thank you I was unaware of the advanced formatting.
