### ISSUE TITLE
Error when using IN and NOTIN operators with multiple values

### ISSUE THREAD

**Issue by codepattern** [sensu/grafana-sensu-go-datasource#46]
Hi, 

Attempting to use in and notin operators with multiple values, it seems to fail based on the expectation that it should be a list.

Object
request:Object
method:"GET"
url:"api/datasources/proxy/1/api_key_auth/api/core/v2/namespaces/engineering/events"
params:Object
fieldSelector:"event.check.status == "2""
labelSelector:"annotations.sample "(ABC|DEF|HIJ)""
hideFromInspector:false
response:Object
message:"could not parse the operations: found '(ABC|DEF|HIJ)', expected '['"
code:1

**Comment by mariusoe** [comment]
Fixed in #64
