### ISSUE TITLE
Resolve shelljs security alert

### ISSUE THREAD

**Issue by apaskulin** [sensu/grafana-sensu-go-datasource#5]
https://github.com/sensu/grafana-sensu-go-datasource/network/alert/package-lock.json/shelljs/open

**Comment by cwjohnston** [comment]
Per https://github.com/shelljs/shelljs/issues/945#issuecomment-505094896 resolving this alert depends on understanding where we use shelljs and ensuring that inputs sanitized appropriately anywhere we might be using the library’s `exec` function.

**Comment by cwjohnston** [comment]
@mariusoe will you please comment on how shelljs is being used in this project? It's not clear to me if there's anything we can do to address this alert directly in this project.

**Comment by mariusoe** [comment]
All security alerts have been resolved and verified that they are not breaking anything
