### ISSUE TITLE
LIMIT is applied to aggregated queries

### ISSUE THREAD

**Issue by timbutler** [sensu/grafana-sensu-go-datasource#8]
The default for a field type data query is to limit the results to 100. However, when the selector is changed to _Aggregation_, the limit still applies but the limit field is removed from view.

This means a query where you want to return a count of the entities, it will always be 100 if the numbers are greater than 100.

As I can see that the aggregation is Grafana / browser side, I'm not sure if the limit should be removed completely or at least displayed to allow an override.

**Comment by mariusoe** [comment]
Should be solved by PR #11
