### ISSUE TITLE
Broken in 6.3+ Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by ninjasloth22** [sensu/grafana-sensu-go-datasource#9]
On Grafana 6.3.0+ and I am getting an error when using the plugin
"Cannot read property 'map' of undefined"

Downgrading to anything prior to 6.3 fixes the issue. 
I'm unsure what has changed between versions to cause this. 

From the browser console during dashboard loading:

Panel data error: TypeError: Cannot read property 'map' of undefined
    at h (SlideDown.tsx:38)
    at PanelQueryState.ts:304

**Comment by mariusoe** [comment]
Should be solved by PR #10
